"""add system_config table

Revision ID: 4721eb22fef2
Revises: 5ecf0c0005ac
Create Date: 2026-05-10 10:56:16.709989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4721eb22fef2'
down_revision = '5ecf0c0005ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('config_type', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_config_key'), ['config_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_config_key'))

    op.drop_table('system_config')
    # ### end Alembic commands ###
