"""initial schema

Revision ID: 5ecf0c0005ac
Revises: 
Create Date: 2026-05-10 10:41:06.092222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecf0c0005ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arete', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('breed', sa.String(length=64), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arete')
    )
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(length=256), nullable=True),
    sa.Column('annotated_path', sa.String(length=256), nullable=True),
    sa.Column('n_detections', sa.Integer(), nullable=True),
    sa.Column('detections_json', sa.JSON(), nullable=True),
    sa.Column('eye_results', sa.JSON(), nullable=True),
    sa.Column('leg_results', sa.JSON(), nullable=True),
    sa.Column('has_anomaly', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('findings_json', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('vet_report', sa.Text(), nullable=True),
    sa.Column('conf_threshold', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_has_anomaly'), ['has_anomaly'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_timestamp'))
        batch_op.drop_index(batch_op.f('ix_analyses_has_anomaly'))

    op.drop_table('analyses')
    op.drop_table('animals')
    op.drop_table('users')
    # ### end Alembic commands ###
